version: '3.8'

services:
  php:
    build:
      context: ./app/docker/conf/php
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - main_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./app/docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main_network
    depends_on:
      - php
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: ${APP_NAME}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  main_network:
    driver: bridge
    name: ${APP_NAME}-main-network
    ipam:
      driver: default